databases:
  - name: my_budget_app_db
   ipAllowList: []

services:
  - type: web
    name: falis--app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  my_budget_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      -type: redis
       name: redis
       ipAllowList: []
       maxmemoryPolicy: noeviction



